name: CI

on: [push, pull_request]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        enable-stack: true

    - name: Cache Stack dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.setup-haskell.outputs.stack-root }}
          .stack-work
        key: ${{ runner.os }}-stack-test-${{ hashFiles('**/stack.yaml.lock', '**/package.yaml', '**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-stack-test

    - run: stack test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}           
      with:
        name: test-results
        path: junit.xml
  
  # Only trigger release on main branch
  release:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: ./.github/workflows/release.yml