name: CI

on: [push, pull_request]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        enable-stack: true

    - name: Cache Stack dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock', '**/package.yaml', '**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - run: stack test
    - name: Publish test results
      uses: dorny/test-reporter@v2
      if: ${{ !cancelled() }} 
      with:
        name: Test Results
        path: junit.xml
        reporter: java-junit

    - run: stack build

    - name: Find executable
      id: find-exe
      run: |
        EXEC_PATH=$(stack path --local-install-root)/bin/fancy-police
        echo "path=$EXEC_PATH" >> $GITHUB_OUTPUT

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: fancy-police-${{ runner.os }}
        path: ${{ steps.find-exe.outputs.path }} 