name: Release Build

on:
  workflow_call:  # Make it reusable

jobs:
  build-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        enable-stack: true

    - name: Cache Stack dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock', '**/package.yaml', '**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - run: stack build

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: fancy-police-${{ runner.os }}
        path: |
          .stack-work/install/*/bin/fancy-police
          .stack-work/install/*/bin/fancy-police.exe