name: Release Build

on:
  push:
    tags:
      - 'v*'  # Triggers on v1.0.0, v2.1.3, etc.

permissions:
  contents: write     
  actions: read 

jobs:
  build-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        enable-stack: true
    
    - name: Cache Stack dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ steps.setup-haskell.outputs.stack-root }}
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock', '**/package.yaml', '**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    
    - run: stack build

    - name: Prepare release artifacts  
      shell: bash
      run: |
        mkdir -p release
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          find .stack-work/install -name "fancy-police.exe" -exec cp {} release/fancy-police-Windows.exe \;
        else
          find .stack-work/install -name "fancy-police" -exec cp {} release/fancy-police-${{ runner.os }} \;
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: release/*
        generate_release_notes: true
